### ISSUE TITLE
File operations do not work on the disk branch

### ISSUE THREAD

**Issue by Goldside543** [Goldside543/goldspace#21]
Related to #20. 

The disk branch, where I am trying to make the BFFS file system disk-based, is getting incredibly hard to manage, and file operations no longer work on it.

**Comment by kss682** [comment]
I'm a total newbie to kernel development but would like to get into it. I would like to work on this issue or if there is any other issue that is beginner friendly.

**Comment by Goldside543** [comment]
> I'm a total newbie to kernel development but would like to get into it. I would like to work on this issue or if there is any other issue that is beginner friendly.

Take a look at issue #22. You could learn the code and write about it. Thanks for your interest in Goldspace!

**Comment by Goldside543** [comment]
Closing this issue as not planned, as I am restarting progress on the drivers.
